on:
  push:
    branches:
      - main
      - dev

jobs:
  units-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.2

      - name: Activate Python virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Upgrade pip and install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Set up Pytest
        run: |
          cd signa2text
          pytest
